
GET https://api.wallapop.com/api/v3/users/user_id

GET https://api.wallapop.com/api/v3/users/user_id/items

GET https://api.wallapop.com/api/v3/users/user_id/reviews

GET https://api.wallapop.com/api/v3/users/user_id/items?category_id=100

GET https://api.wallapop.com/api/v3/items/user_id

